name: Deploy app - AWS

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - ".github/workflows/app-aws.yml"

jobs:
  setup-build-deploy:
    name: Build and deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Deploy to Web
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Enter folder
        run: cd /home/${{ secrets.USERNAME }}/cantodaruaemergencial/app

      - name: Install
        run: npm i

      - name: Build
        run: npm run build

      - name: PM2 start
        run: pm2 start web.cantodaruaemergencial

      - name: PM2 save
        run: pm2 save
