name: Deploy app - AWS

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - ".github/workflows/app-aws.yml"

env:
  USERNAME: ${{ secrets.USERNAME }}

jobs:
  setup-build-deploy:
    name: Build and deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build

      - name: Deploy to Web
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: PM2 start
        run: |
          pm2 start web.cantodaruaemergencial

      - name: PM2 save
        run: |
          pm2 save
