name: Deploy app - AWS

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - ".github/workflows/app-aws.yml"

jobs:
  setup-build-deploy:
    name: Build and deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Build & Deploy
        uses: actions/checkout@v2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOSTNAME: ${{ secrets.HOST_DNS }}
          USER_NAME: ${{ secrets.USERNAME }}

      - name: Run commands
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}

              # Now we have got the access of EC2 and we will start the deploy .
              cd /home/ubuntu/cantodaruaemergencial &&
              git checkout main &&
              git fetch --all &&
              git reset --hard origin/main &&
              git pull origin main &&
              sudo npm i &&
              sudo npm run build &&
              cd ~ &&
              sudo pm2 stop web.cantodaruaemergencial &&
              sudo pm2 delete web.cantodaruaemergencial &&
              sudo pm2 start ecosystem.config.js &&
              sudo pm2 save
